#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# NVM
[ -s "/Users/dtinth/.nvm/nvm.sh" ] && . "/Users/dtinth/.nvm/nvm.sh" # This loads nvm

# https://github.com/nvbn/thefuck
alias fuck='$(thefuck $(fc -ln -1))'

# Use neovim instead of vim
alias vim=nvim

# Aliases from oh-my-zsh
alias gst='git status'
alias gaa='git add -A'

# Stuffs
export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH="$HOME/.yarn/bin:$PATH"
