#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -s "/Users/dtinth/.nvm/nvm.sh" ] && . "/Users/dtinth/.nvm/nvm.sh" # This loads nvm

alias fuck='$(thefuck $(fc -ln -1))'
alias vim=nvim
alias gst='git status'
alias gaa='git add -A'
export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH="$HOME/.yarn/bin:$PATH"
