#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# https://github.com/nvbn/thefuck
alias fuck='$(thefuck $(fc -ln -1))'

# Use neovim instead of vim
alias vim=nvim

# Aliases from oh-my-zsh
alias gst='git status'
alias gaa='git add -A'

# Stuffs
export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH="$HOME/.yarn/bin:$PATH"

# NVM
[ -s ~/.nvm/nvm.sh ] && . ~/.nvm/nvm.sh # This loads nvm

# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
